<h3> Conozca un Arreglo numpy  </h3>

Utilizará el arreglo numpy <code> A</code> para lo siguiente  

In [1]:
import numpy as np
A=np.array([[11,12],[21,22],[31,32]])


1) escriba usando la función 'type' 

In [2]:
type(A)

numpy.ndarray

2) la forma del arreglo 

In [4]:
A.ndim

2

3) el tipo de datos en el arreglo 

In [6]:
A.dtype

dtype('int64')

4) Encuentre la segunda fila del arreglo numpy <code>A</code>:

In [10]:
A
A[1,:]

array([21, 22])

<h3> Dos tipos de Multiplicación    </h3>

utilizará los siguientes arreglos numpy para las siguientes preguntas 

In [11]:
A=np.array([[11,12],[21,22]])
B=np.array([[1, 0],[0,1]])

1) multiplique la matriz <code> A </code> y <code>B</code> 

In [10]:
A*B

array([[11,  0],
       [ 0, 22]])

2) trazar la función

In [12]:
np.dot(A,B)
np.dot(B,A)



array([[11, 12],
       [21, 22]])

<hr>
<small>Copyright &copy 2020 IBM Cognitive Class. Este cuaderno y su código fuente se publican bajo los términos de la [Licencia MIT] (https://cognitiveclass.ai/mit-license/).

</small>

In [24]:
A=np.array([[1,2]])
C=np.array([[1,2]])
B=np.array([[1,2],[4,5],[7,8]])

#np.dot(A,B)
A.ndim
B.ndim

2

In [25]:
np.dot(A,C)

ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)